# This file is a part of SimilaritySearch.jl

using Random: randperm

"""
    omit_element(key::NTuple{N, UInt32}, idx::Int) where N

Returns an (N-1)-tuple obtained by omitting the `idx`-th element from `key`.
"""
@inline function omit_element(key::NTuple{N,UInt32}, idx::Int) where {N}
    ntuple(j -> j < idx ? key[j] : key[j+1], N - 1)
end

"""
    sample_other_subgroup_element(groups::Vector{Vector{UInt32}}, current_group_idx::Int)

Samples a random element from any sub-group in `groups` except `groups[current_group_idx]`.
"""
function sample_other_subgroup_element(groups::Vector{Vector{UInt32}}, current_group_idx::Int)
    m = length(groups)
    m <= 1 && return nothing
    j = rand(1:(m-1))
    j >= current_group_idx && (j += 1)
    g = groups[j]
    return g[rand(1:length(g))]
end

"""
    link_clusters!(adj_sets::Vector{Set{UInt32}}, clusters, n_neighbors::Integer)

Links newly merged sub-groups at the current prefix level:
1. Connects the first element of each merged sub-group to the first element of `groups[1]`.
2. Connects elements to `n_neighbors` (ñ) random elements belonging to OTHER sub-groups in the merged cluster.
Sub-groups that were already merged in previous steps are deduplicated via `Set` and not re-linked internally.
All links are non-directed (undirected).
"""
function link_clusters!(adj_sets::Vector{Set{UInt32}}, clusters, n_neighbors::Integer)
    for groups_set in values(clusters)
        m = length(groups_set)
        m <= 1 && continue
        groups = collect(groups_set)

        # 1. Connect first element of each sub-group to first element of groups[1]
        main_rep = first(groups[1])
        for i in 2:m
            g_rep = first(groups[i])
            if g_rep != main_rep
                push!(adj_sets[g_rep], main_rep)
                push!(adj_sets[main_rep], g_rep)
            end
        end

        # 2. Connect elements to n_neighbors random elements in OTHER sub-groups
        if n_neighbors > 0
            for gi_idx in 1:m
                gi = groups[gi_idx]
                for u in gi
                    for _ in 1:n_neighbors
                        v = sample_other_subgroup_element(groups, gi_idx)
                        if v !== nothing && v != u
                            push!(adj_sets[u], v)
                            push!(adj_sets[v], u)
                        end
                    end
                end
            end
        end
    end
end

"""
    flatten_clusters(clusters::Dict{K,V}) where {K,V}

Flattens deduplicated sub-group sets in `clusters` into a single `Vector{UInt32}` per key for the next iteration.
"""
function flatten_clusters(clusters::Dict{K,V}) where {K,V}
    flat = Dict{K,Vector{UInt32}}()
    for (key, groups_set) in clusters
        flat[key] = reduce(vcat, groups_set)
    end
    flat
end

"""
    index!(idx::SearchGraph, ctx::SearchGraphContext, ::Val{:knr},
           knr_ids::Matrix{UInt32}, knr_dists::Matrix{Float32};
        n_neighbors::Integer=2,
        hints_size::Int=100,
        start_factor::Float64=0.97,
    )

Fast non-incremental construction of a `SearchGraph` index using hierarchical combination clusters of nearest references.
Groups start at length `k`, and each subsequent level `L` table is generated by taking all combinations of size `L` from the
length `L+1` keys. Duplicate sub-clusters are deduplicated using `Set` before linking.
"""
function index!(idx::SearchGraph, ctx::SearchGraphContext, ::Val{:knr},
                knr_ids::Matrix{UInt32}, knr_dists::Matrix{Float32};
    n_neighbors::Integer=2,
    hints_size::Int=100,
    expansion_limit::Int=16,
    start_factor::Float64=0.97,
)
    k, n = size(knr_ids)
    @assert size(knr_dists) == (k, n)
    length(idx) == 0 || throw(ArgumentError("This construction method accepts only not previously created graphs"))
    n == length(database(idx)) || throw(ArgumentError("The given knr matrix doesn't correspond with the given index: sizes don't match"))
    n > size(knr_ids, 1) >= k >= 1 || throw(ArgumentError("The following must be ensured: |db| > numrefs >= k >= 1"))
    n >= hints_size || throw(ArgumentError("hints_size cannot be larger than the dataset"))
    n_neighbors >= 0 || throw(ArgumentError("n_neighbors must be non-negative"))
    start_factor >= 0 || throw(ArgumentError("start_factor must be non-negative"))
    expansion_limit >= 2 || throw(ArgumentError("expansion_limit must be >= 2"))

    adj_sets = [Set{UInt32}() for _ in 1:n]

    # Initial grouping by longest prefix length L = k (each object starts in a 1-element vector)

    flat_clusters = nothing
    while k >= 1
        flat_clusters = Dict{NTuple{k,UInt32},Vector{UInt32}}()
        for objID in 1:n
            prefix = ntuple(i -> knr_ids[i, objID], k)
            L = get!(Vector{UInt32}, flat_clusters, prefix)
            push!(L, objID)
        end

        np = length(flat_clusters)

        verbose(ctx) && @inform ctx "knr> k=$k, np=$np"
        
        if np > start_factor * n
            k -= 1
        else
            link_clusters!(adj_sets, [[v] for v in values(flat_clusters)], n_neighbors)
            break
        end
    end

    # Hierarchical merging down from L = k - 1 to 1 using combinations of size L from L+1 keys

    #LOCKS = [Threads.SpinLock() for _ in 1:n]
    for L in (k-1):-1:1
        next_clusters = Dict{NTuple{L,UInt32},Base.IdSet{Vector{UInt32}}}()
        verbose(ctx) && @inform ctx "knr> flat_clusters before: $(quantile(length.(values(flat_clusters)), 0:0.1:1))"
        for (key, flat_group) in flat_clusters
            if length(flat_group) > expansion_limit
                sub_key = omit_element(key, 0)
                push!(get!(Base.IdSet{Vector{UInt32}}, next_clusters, sub_key), flat_group)
            else
                for i in 1:(L+1)
                    sub_key = omit_element(key, i)
                    push!(get!(Base.IdSet{Vector{UInt32}}, next_clusters, sub_key), flat_group)
                end
            end
        end

        link_clusters!(adj_sets, next_clusters, n_neighbors)
        flat_clusters = flatten_clusters(next_clusters)
        verbose(ctx) && @inform ctx "knr> flat_clusters after: $(quantile(length.(values(flat_clusters)), 0:0.1:1))"

        quant = quantile(length.(adj_sets), 0:0.1:1)
        verbose(ctx) && @inform ctx "knr> adjacency-size quantiles: $quant"
        first(quant) >= 1 && break
    end

    # Hints selection based on highest node degrees
    let H = collect(zip(1:n, length.(adj_sets)))
        sort!(H, by=last, rev=true)
        empty!(idx.hints)
        for h in H
            push!(idx.hints, first(h))
            length(idx.hints) < hints_size || break
        end
    end
    verbose(ctx) && @inform ctx "knr> hints: $(length(idx.hints))"

    resize!(idx.adj, n)
    for i in 1:n
        add!(idx.adj, i, collect(adj_sets[i]))
    end

    idx.len[] = n
    idx
end

"""
    index!(idx::SearchGraph, ctx::SearchGraphContext, kind::Val{:knr};
        numrefs::Integer=ceil(Int, sqrt(length(database(idx)))),
        k::Integer=4,
        sample_method::Symbol=:fft,
        n_neighbors::Integer=2,
        hints_size::Int=100,
        start_factor::Float64=0.97
    )

Computes the `knr` projection matrix using `numrefs` references and calls `index!(idx, ctx, Val(:knr), knr)`.
Progress is reported through `ctx`: `verbose(ctx)` decides whether the messages are produced,
`ctx.reporters` where they go.
"""
function index!(idx::SearchGraph, ctx::SearchGraphContext, kind::Val{:knr};
    numrefs::Integer=ceil(Int, sqrt(length(database(idx)))),
    k::Integer=4,
    sample_method::Symbol=:fft, #:random, :fft
    n_neighbors::Integer=2,
    hints_size::Int=100,
    start_factor::Float64=0.97
)
    dist = distance(idx)
    db = database(idx)
    n = length(db)

    ref_ids = if sample_method === :fft
        elapsed = @elapsed fft_res = fft(dist, db, numrefs; verbose=verbose(ctx), reporters=ctx.reporters)
        verbose(ctx) && @inform ctx "knr> fft (center selection) took $(round(elapsed; digits=3))s"
        fft_res.centers
    elseif sample_method === :random
        randperm(n)[1:numrefs]
    else
        throw(ArgumentError("Unknown sample_method: $sample_method. Use :fft or :random"))
    end

    sort!(ref_ids)
    refs_db = SubDatabase(db, ref_ids)

    # Project DB onto references via searchbatch on ExhaustiveSearch
    seq = ExhaustiveSearch(dist, refs_db)
    ectx = GenericContext(KnnSorted)
    knr_ids, knr_dists = searchbatch(seq, ectx, db, k) # size (k, n)
    index!(idx, ctx, kind, knr_ids, knr_dists; n_neighbors, hints_size, start_factor)
end

"""
    index!(idx::SearchGraph, ctx::SearchGraphContext, kind::Val{:bitsketch};
        method::Symbol=:gaussian,
        nbits::Int=256,
        kind::ErrorFunction=MaxMatchError(; maxerror=0.01f0),
        logbase::Float32=1.3f0,
        parallel_block::Int=2^13
    )

Fast non-incremental construction of a `SearchGraph` via a cheap proxy space: `database(idx)`
is sketched into an `nbits`-bit sign sketch (`method`, see
[`SimilaritySearch.Projections.bitsketch`](@ref)), a topology is built over that sketch under
[`Dist.Bits.Hamming`](@ref) using the normal incremental [`index!`](@ref) (tuned towards
`kind`), and that topology (adjacency + hints -- *not* the sketch-space-tuned `BeamSearch`,
see below) is copied into `idx`, which keeps its own real `distance(idx)`/`database(idx)` for
serving.

This grew out of a long investigation (issue #52) into `:knr`'s hierarchical-clustering
construction, which turned out to (a) scale badly on real, high-dimensional embeddings (its
own construction cost, not just the resulting recall) and (b) need a [`rebuild`](@ref) pass
afterward to fix its hub-heavy degree distribution -- one whose own quality turned out to
depend entirely on `algo[]`'s carried-over `maxvisits` (issue #59, now fixed) and whose net
effect on recall was inconsistent and hard to predict. Sketching into a proper bit-sketch
(not just a handful of reference ids, `:knr`'s approach) and building the topology via the
already-well-tested incremental `index!` sidesteps both problems: no combinatorial clustering
algorithm to scale badly, and -- per repeated measurement against a real ~600k-row embedding
slice, confirmed at `n=100_000` and `n=200_000` with a fixed seed -- no `rebuild` pass needed
to reach a competitive recall/QpS trade-off against an equal-effort incremental build.

!!! warning "`method=:gaussian`/`:qr` only work for vector-represented databases"
    The default rotation-based sketch methods (`:gaussian`, `:qr`) require `database(idx)` to
    be matrix-like (a [`MatrixDatabase`](@ref)): they compute a random rotation of the raw
    coordinate vectors and keep the sign of each resulting coordinate, which is only
    meaningful when the objects actually *are* vectors in a Euclidean-ish space. A metric
    space without a vector representation (edit distance over strings, an arbitrary user type
    compared through a custom [`SemiMetric`](@ref), ...) cannot use `:gaussian`/`:qr`; a
    hyperplane-based sketch such as [`AnchoredDistantHyperplanes`](@ref) (which only needs
    `dist`/`evaluate`, no vector coordinates) is the right tool there instead -- but it is not
    yet wired into `:bitsketch` as a `method` option.

!!! note "Only accepts an empty `idx`, and doesn't (yet) support incremental growth"
    Like `:knr`, this only accepts an `idx` with `length(idx) == 0` (`database(idx)` must
    already hold the whole dataset to sketch, but no vertex may exist in the graph yet), and
    rebuilds the whole topology from scratch every call -- there is no way to grow an
    existing `:bitsketch`-built graph by inserting new items afterward. A proper two-stage
    index design that supports incremental insertion on top of a fast bootstrap phase like
    this one is tracked as a separate feature request (issue #60); for a workload that needs
    online insertion today, use the normal incremental `index!(idx, ctx)` instead.

`idx.algo[]` is deliberately left untouched (never overwritten with the sketch-space-tuned
`BeamSearch`): its `bsize`/`Δ`/`maxvisits` were tuned for Hamming distance's very different
scale, and carrying that over would silently miscalibrate every later search/optimize call
against `idx`'s real distance (the exact bug fixed in issue #59, there for [`rebuild`](@ref)).
Call [`optimize_index!`](@ref) once `idx` is populated, same as after any other construction
method.

If, after tuning, the resulting recall/QpS trade-off isn't good enough, a further
[`rebuild`](@ref) pass against the real `distance(idx)`/`database(idx)` is worth trying --
it is not required or applied automatically here, since in repeated measurement it did not
reliably improve on the plain sketch-built topology (see issue #52).

# Keyword Arguments
- `method`: the bit-sketch generator, `:gaussian` (default) or `:qr` -- see
  [`SimilaritySearch.Projections.bitsketch`](@ref); see the vector-space warning above.
- `nbits`: sketch width in bits, must be a multiple of 64 (default `256`, i.e. 4 `UInt64`
  words). A wider sketch costs more memory/compute per comparison but tends to improve
  recall; see issue #52 for measurements across 64-1536 bits on real embeddings.
- `kind`: the [`ErrorFunction`](@ref) `OptimizeParameters`/[`optimize_index!`](@ref) tunes the
  sketch-space construction towards (default `MaxMatchError(; maxerror=0.01f0)`, calibrated
  to roughly match `MinRecall(0.9)`'s achieved quality on real embeddings while building
  noticeably faster and far more consistently run-to-run -- see issue #52's measurements).
  Pass `MinRecall(...)` to use the more familiar identifier-set-based criterion instead.
- `logbase`: log base for the sketch-space `Neighborhood`'s size growth, see [`Neighborhood`](@ref).
- `parallel_block`: forwarded as the sketch-space construction's own `parallel_block`
  (size of the batch processed in parallel at a time), see [`SearchGraphContext`](@ref).
"""
function index!(idx::SearchGraph, ctx::SearchGraphContext, ::Val{:bitsketch};
    method::Symbol=:gaussian,
    nbits::Int=256,
    kind::ErrorFunction=MaxMatchError(; maxerror=0.01f0),
    logbase::Float32=1.3f0,
    parallel_block::Int=2^13
)
    length(idx) == 0 || throw(ArgumentError("index!(...; :bitsketch): this construction method accepts only not-previously-created indexes"))
    nbits % 64 == 0 || throw(ArgumentError("index!(...; :bitsketch): nbits=$nbits must be a multiple of 64"))

    db = database(idx)
    n = length(db)
    n > 0 || throw(ArgumentError("index!(...; :bitsketch): database(idx) is empty"))
    db isa MatrixDatabase || throw(ArgumentError("index!(...; :bitsketch): method=:$method needs database(idx) to be a MatrixDatabase (vector-represented); a non-vector metric space needs a hyperplane-based sketch (e.g. AnchoredDistantHyperplanes) instead of :gaussian/:qr -- not yet wired into :bitsketch"))

    B, _ = Projections.bitsketch(method, nbits, db.matrix)
    sketch_graph = SearchGraph(Dist.Bits.Hamming(), MatrixDatabase(B))
    sketch_ctx = SearchGraphContext(
        neighborhood=Neighborhood(; filter=SatNeighborhood(), logbase),
        hyperparameters_callback=OptimizeParameters(kind),
        parallel_block=parallel_block,
        reporters=ctx.reporters,
        verbose=verbose(ctx)
    )
    index!(sketch_graph, sketch_ctx)

    resize!(idx.adj, n)
    for i in 1:n
        add!(idx.adj, i, collect(neighbors(sketch_graph.adj, i)))
    end
    empty!(idx.hints)
    append!(idx.hints, sketch_graph.hints)
    idx.len[] = n

    verbose(ctx) && @inform ctx "bitsketch> built $nbits-bit ($method) sketch topology, hints: $(length(idx.hints))"
    idx
end
