# This file is a part of SimilaritySearch.jl

using Random: randperm

"""
    omit_element(key::NTuple{N, UInt32}, idx::Int) where N

Returns an (N-1)-tuple obtained by omitting the `idx`-th element from `key`.
"""
@inline function omit_element(key::NTuple{N,UInt32}, idx::Int) where {N}
    ntuple(j -> j < idx ? key[j] : key[j+1], N - 1)
end

"""
    sample_other_subgroup_element(groups::Vector{Vector{UInt32}}, current_group_idx::Int)

Samples a random element from any sub-group in `groups` except `groups[current_group_idx]`.
"""
function sample_other_subgroup_element(groups::Vector{Vector{UInt32}}, current_group_idx::Int)
    m = length(groups)
    m <= 1 && return nothing
    j = rand(1:(m-1))
    j >= current_group_idx && (j += 1)
    g = groups[j]
    return g[rand(1:length(g))]
end

"""
    link_clusters!(adj_sets::Vector{Set{UInt32}}, clusters::Dict, n_neighbors::Integer)

Links newly merged sub-groups at the current prefix level:
1. Connects the first element of each merged sub-group to the first element of `groups[1]`.
2. Connects elements to `n_neighbors` (ñ) random elements belonging to OTHER sub-groups in the merged cluster.
Sub-groups that were already merged in previous steps are deduplicated via `Set` and not re-linked internally.
All links are non-directed (undirected).
"""
function link_clusters!(adj_sets::Vector{Set{UInt32}}, clusters::Dict, n_neighbors::Integer)
    for groups_set in values(clusters)
        m = length(groups_set)
        m <= 1 && continue
        groups = collect(groups_set)

        # 1. Connect first element of each sub-group to first element of groups[1]
        main_rep = first(groups[1])
        @inbounds for i in 2:m
            g_rep = first(groups[i])
            if g_rep != main_rep
                push!(adj_sets[g_rep], main_rep)
                push!(adj_sets[main_rep], g_rep)
            end
        end

        # 2. Connect elements to n_neighbors random elements in OTHER sub-groups
        if n_neighbors > 0
            @inbounds for gi_idx in 1:m
                gi = groups[gi_idx]
                for u in gi
                    for _ in 1:n_neighbors
                        v = sample_other_subgroup_element(groups, gi_idx)
                        if v !== nothing && v != u
                            push!(adj_sets[u], v)
                            push!(adj_sets[v], u)
                        end
                    end
                end
            end
        end
    end
end

"""
    flatten_clusters(clusters::Dict{K,V}) where {K,V}

Flattens deduplicated sub-group sets in `clusters` into a single `Vector{UInt32}` per key for the next iteration.
"""
function flatten_clusters(clusters::Dict{K,V}) where {K,V}
    flat = Dict{K,Vector{UInt32}}()
    for (key, groups_set) in clusters
        flat[key] = reduce(vcat, groups_set)
    end
    flat
end

"""
    index!(idx::SearchGraph, ctx::SearchGraphContext, ::Val{:knr}, knr::Matrix{IdDist};
        n_neighbors::Integer=2,
        hints_size::Int=100,
        min_link::Int=1,
    )

Fast non-incremental construction of a `SearchGraph` index using hierarchical combination clusters of nearest references.
Groups start at length `k`, and each subsequent level `L` table is generated by taking all combinations of size `L` from the
length `L+1` keys. Duplicate sub-clusters are deduplicated using `Set` before linking.
"""
function index!(idx::SearchGraph, ::SearchGraphContext, ::Val{:knr}, knr::Matrix{IdDist};
    n_neighbors::Integer=2,
    hints_size::Int=100,
    min_link::Int=1,
)
    k, n = size(knr)
    length(idx) == 0 || throw(ArgumentError("This construction method accepts only not previously created graphs"))
    n == length(database(idx)) || throw(ArgumentError("The given knr matrix doesn't correspond with the given index: sizes don't match"))
    n > size(knr, 1) >= k >= 1 || throw(ArgumentError("The following must be ensured: |db| > numrefs >= k >= 1"))
    n >= hints_size || throw(ArgumentError("hints_size cannot be larger than the dataset"))
    n_neighbors >= 0 || throw(ArgumentError("n_neighbors must be non-negative"))
    min_link >= 0 || throw(ArgumentError("min_link must be non-negative"))

    adj_sets = [Set{UInt32}() for _ in 1:n]

    # Initial grouping by longest prefix length L = k (each object starts in a 1-element vector)

    local flat_clusters
    while k >= 1
        clusters = Dict{NTuple{k,UInt32},Vector{Vector{UInt32}}}()
        for objID in 1:n
            prefix = ntuple(i -> knr[i, objID].id, k)
            L = get(clusters, prefix, nothing)
            if L === nothing
                clusters[prefix] = Vector{UInt32}[UInt32[objID]]
            else
                push!(L[1], objID)
            end
        end

        np = length(clusters)

        @info "k=$k, np=$np"
        if np > 0.97 * length(adj_sets)
            k -= 1
            for a in adj_sets
                empty!(a)
            end
        else
            link_clusters!(adj_sets, clusters, n_neighbors)
            flat_clusters = flatten_clusters(clusters)
            break
        end
    end


    # Hierarchical merging down from L = k - 1 to 1 using combinations of size L from L+1 keys

    for L in (k-1):-1:1
        next_clusters = Dict{NTuple{L,UInt32},Base.IdSet{Vector{UInt32}}}()
        for (key, flat_group) in flat_clusters
            for i in 1:(L+1)
                sub_key = omit_element(key, i)
                push!(get!(Base.IdSet{Vector{UInt32}}, next_clusters, sub_key), flat_group)
            end
        end

        link_clusters!(adj_sets, next_clusters, n_neighbors)
        flat_clusters = flatten_clusters(next_clusters)

        quant = quantile(length.(adj_sets), 0:0.1:1)
        @show quant
        first(quant) >= min_link && break
    end

    # Hints selection based on highest node degrees
    let H = collect(zip(1:n, length.(adj_sets)))
        sort!(H, by=last, rev=true)
        empty!(idx.hints)
        for h in H
            push!(idx.hints, first(h))
            length(idx.hints) < hints_size || break
        end
    end
    @show length(idx.hints)

    resize!(idx.adj, n)
    for i in 1:n
        add!(idx.adj, i, collect(adj_sets[i]))
    end

    idx.len[] = n
    idx
end

"""
    index!(idx::SearchGraph, ctx::SearchGraphContext, kind::Val{:knr};
        numrefs::Integer=ceil(Int, sqrt(length(database(idx)))),
        k::Integer=4,
        sample_method::Symbol=:fft,
        n_neighbors::Integer=2,
        hints_size::Int=100,
        min_link::Int=1,
        verbose::Bool=true
    )

Computes the `knr` projection matrix using `numrefs` references and calls `index!(idx, ctx, Val(:knr), knr)`.
"""
function index!(idx::SearchGraph, ctx::SearchGraphContext, kind::Val{:knr};
    numrefs::Integer=ceil(Int, sqrt(length(database(idx)))),
    k::Integer=4,
    sample_method::Symbol=:fft, #:random, :fft
    n_neighbors::Integer=2,
    hints_size::Int=100,
    min_link::Int=1,
    verbose::Bool=true
)
    dist = distance(idx)
    db = database(idx)
    n = length(db)

    ref_ids = if sample_method === :fft
        @time "fft (center selection)" fft_res = fft(dist, db, numrefs; verbose)
        fft_res.centers
    elseif sample_method === :random
        randperm(n)[1:numrefs]
    else
        throw(ArgumentError("Unknown sample_method: $sample_method. Use :fft or :random"))
    end

    sort!(ref_ids)
    refs_db = SubDatabase(db, ref_ids)

    # Project DB onto references via searchbatch on ExhaustiveSearch
    seq = ExhaustiveSearch(dist, refs_db)
    ectx = GenericContext(KnnSorted)
    knr = searchbatch(seq, ectx, db, k) # size (k, n)
    index!(idx, ctx, kind, knr; n_neighbors, hints_size, min_link)
end
